# roles/mariadb/tasks/install.yml
---

- name: Add official MariaDB repository
  yum_repository:
    name: MariaDB
    description: Official MariaDB repository
    baseurl: "http://{{ mariadb_mirror }}/{{ mariadb_version }}/rhel{{ ansible_distribution_major_version }}-amd64"
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: false
  tags: mariadb

- name: Install packages
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ mariadb_packages }}"
  tags: mariadb
