---
# tasks file for mariadb

- name: Assign variables
  include_vars: "{{ item }}"
  with_first_found:
        - "vars/CentOS-{{ ansible_distribution_major_version }}.yml"
  tags: mariadb

- include_tasks: install.yml
- include_tasks: config.yml
- include_tasks: root-password.yml
- include_tasks: databases.yml
- include_tasks: users.yml
